### ISSUE TITLE
The font collector does not work as it should

### ISSUE THREAD

**Issue by Makabra** [Ristellise/AegisubDC#1]
Above Daydream build, below build 8993 
![unknown (1)](https://user-images.githubusercontent.com/7323474/89928897-56d01200-dbbd-11ea-8e0f-9118728797f0.png)

It seems the problem is when there is more than one type of the family font. Take the regular one even if it hasn't been use.

**Comment by Ristellise** [comment]
> Above Daydream build, below build 8993
Which build exactly?

**Comment by Makabra** [comment]
Yes, is the 9203.

**Comment by Ristellise** [comment]
I think I see the issue here, but I think it will be too hard to fix as you would have to read all the font files (Which might take a while!) and then checking them which takes even longer time. Might be not worth the time for it :/

**Comment by Ristellise** [comment]
Thanks to a hint from Ryoka on discord, narrowed down to: https://github.com/wangqr/Aegisub/commit/cd7ee8d5055b04764fc3e396cc2ab118d093f1ae

I might have a look at it soon enough...

**Comment by Ristellise** [comment]
Fixed in `9205 - Petzku's Club`
