### ISSUE TITLE
SRT time doesn't seem to be converted properly

### ISSUE THREAD

**Issue by matheousse** [Ristellise/AegisubDC#11]
I was OCR some Wakanim hardsubbed video with YoloCR, which is known for having next to no time/ocr issues, but to my surprise a lot of lines were mistimed by 1 frame (see first screenshot). I then asked a friend to ocr the same video with the exact same settings, and when he opened the file, everything was fine (he was using 8992).
I came to the conclusion that something must be going wrong with AegiDC. (most likely the decimal rounding, because the line started at .247 in the SRT and got rounded at .24 on 8992, and .25 on DC, which cause the desync) 

(8992 friend file) ![Time Aegisub 8992](https://user-images.githubusercontent.com/39730615/106339665-8ec83000-6297-11eb-84b8-ff65f470ea98.png)
(my DC 9211 file) ![Time AegisubDC 9211](https://user-images.githubusercontent.com/39730615/106339672-925bb700-6297-11eb-8202-52683e95a900.png)

**Comment by Ristellise** [comment]
kindly send a trimmed down video sample and srt subs, thanks.

**Comment by matheousse** [comment]
https://mega.nz/file/w3gW0CZb#1EBfznzoWYRau0cqXI6fwEyUCtDPOMgSvYZdDsGLiNg here's the video (I couldn't manage to trim so that it keeps the desync between DC and 8992)

https://mega.nz/file/V6pgHSqD#gW6gOwH7Jbsedt_7LHN8aPJ_kLd112uscWmn6K9_eec and the line, when opened with DC it starts at .25, other versions starts at .24

**Comment by Ristellise** [comment]
Fixed in latest commit: Ristellise/AegisubDC@52033509f199c68a3235da318f1fc391e5bda26e
