### ISSUE TITLE
Error loading some SubsPlease video's

### ISSUE THREAD

**Issue by Gallyion** [Ristellise/AegisubDC#14]
Hi,

So i have been having this strange issue with opening SubsPlease video's, sometimes for certain eps it will give me an error code (and restarting aegisubs doesn't help, it continues to give me an error code) while for others it will open just fine.
Any idea what could be causing this?

![unknown](https://user-images.githubusercontent.com/78819565/107414587-803d0c80-6b12-11eb-886f-4d5ddf0f6b04.png)

**Comment by Ristellise** [comment]
> Hi,
> 
> So i have been having this strange issue with opening SubsPlease video's, sometimes for certain eps it will give me an error code (and restarting aegisubs doesn't help, it continues to give me an error code) while for others it will open just fine.
> Any idea what could be causing this?
> 
> ![unknown](https://user-images.githubusercontent.com/78819565/107414587-803d0c80-6b12-11eb-886f-4d5ddf0f6b04.png)

Which episode please?

**Comment by Gallyion** [comment]
This came from Bungou Stray dogs Wan ep 5, but been having this for plenty of episodes from different seasons

**Comment by Ristellise** [comment]
> This came from Bungou Stray dogs Wan ep 5, but been having this for plenty of episodes from different seasons

Any specific videos you can tell me? Because I've been DLing SubsPls releases when this issue is brought up and haven't had any issues thus far...

**Comment by Gallyion** [comment]
Ooh i see. 
I've got this same problem for ep 44 of Re:zero, Ep 29 of Tensei Shitara Slime Datta Ken, ep 5 of Yuru Camp s2 (even tried 1080p & also didn't work). 
And a few other but can't remember which eps they were (all 720p, hadn't rly tried with 1080p other that Yuru camp which also resulted in the same issue) 

For now the only way i was able to still see the vid was by DLing one of the official aegisub releases & make do with that.

**Comment by Ristellise** [comment]
> Ooh i see.
> I've got this same problem for ep 44 of Re:zero, Ep 29 of Tensei Shitara Slime Datta Ken, ep 5 of Yuru Camp s2 (even tried 1080p & also didn't work).
> And 1 or 2 from 5-toubun & UmaMusume s2, but can't remember which eps they were (all 720p, hadn't rly tried with 1080p other than Yuru camp which also resulted in the same issue)
> 
> For now the only way i was able to still see the vid was by DLing one of the aegisub trunk builds & make do with that.

And for Bungou Stray dogs Wan? Which video did you use?

**Comment by Gallyion** [comment]
Also 720p

**Comment by Ristellise** [comment]
![image](https://user-images.githubusercontent.com/7894419/110247984-d4b89800-7fa9-11eb-9992-4e42cdc2b4b6.png)

Sorry for the late reply, but could you help me check to see your subtitles provider is set to libass? thanks.

**Comment by Gallyion** [comment]
Ohh no it wasn't it was set to vsfiltermod_textsub

**Comment by Ristellise** [comment]
> Ohh no worries, and no it wasn't, it was set to vsfiltermod_textsub
> Ok i just checked and if i use Libass or vsfilter_textsub the video loads, only vsfiltermod gives me the video error

Should be: https://github.com/Ristellise/AegisubDC/issues/22.
