### ISSUE TITLE
video panning missing!!

### ISSUE THREAD

**Issue by Samo99** [Ristellise/AegisubDC#15]
Hey man

I was so happy that you added moex3 video panning to you build and i downloaded your last build but it wasn't there.

Ca you take a look on why it's not working even the rest video option not appearing in the video menu.

**Comment by Ristellise** [comment]
To enable it, you need to go under `options > Advanced > Experiments` and check the `Video Panning` checkbox to enable it.
![image](https://user-images.githubusercontent.com/7894419/108057001-fc909c00-708c-11eb-81e9-d7e92e6951eb.png)

**Comment by Samo99** [comment]
I found it, thank you so much.

"The reset video option I'm looking into it as of now, not sure why it isn't there either."

Oh, so even if you enable it the reset option don't appear in the menu.

**Comment by Ristellise** [comment]
> but even if you enable it you can't move the video.

Tested locally and it works on my end. [Example](https://files.catbox.moe/josk3j.webm)

**Comment by Samo99** [comment]
Thanks for the info about the middle click man but the reset option still not there :(

![1](https://user-images.githubusercontent.com/12115578/108477500-5919d400-72a4-11eb-96ac-9812181de1cd.png)

**Comment by Ristellise** [comment]
> Thanks for the info about the middle click man but the reset option still not there :(
> 
> ![1](https://user-images.githubusercontent.com/12115578/108477500-5919d400-72a4-11eb-96ac-9812181de1cd.png)

You can add it as a hotkey in the options > hotkeys.

**Comment by Samo99** [comment]
> You can add it as a hotkey in the options > hotkeys. `video/reset_pan` or similar.

I can't do that either 
![1](https://user-images.githubusercontent.com/12115578/108618107-65c93400-742c-11eb-988f-eb39b58a6fda.PNG)

**Comment by Ristellise** [comment]
> > You can add it as a hotkey in the options > hotkeys. `video/reset_pan` or similar.
> 
> I can't do that either
> ![1](https://user-images.githubusercontent.com/12115578/108618107-65c93400-742c-11eb-988f-eb39b58a6fda.PNG)

> or similar

it should be `video/pan_reset`.

**Comment by Samo99** [comment]
> it should be `video/pan_reset`.

Perfect, thank you man it worked.
