### ISSUE TITLE
Stereo audio playback

### ISSUE THREAD

**Issue by logarrhythmic** [Ristellise/AegisubDC#18]
Would it be at all possible to allow audio to play in stereo? I would consider this a drastic improvement, especially when using headphones.

Currently, audio plays in mono. I assume this is because a mono track needs to be created for the waveform/spectrum display, which is then also used for playback, possibly to ensure precision between what's heard and what's shown in the spectrum. However, this leads to reduced audio quality, making it more difficult to hear lyrics and other words correctly, and even the rare omission of sounds such as the background vocals in one of Trinity Seven's openings.

**Comment by Ristellise** [comment]
> Would it be at all possible to allow audio to play in stereo? I would consider this a drastic improvement, especially when using headphones.
> 
> Currently, audio plays in mono. I assume this is because a mono track needs to be created for the waveform/spectrum display, which is then also used for playback, possibly to ensure precision between what's heard and what's shown in the spectrum. However, this leads to reduced audio quality, making it more difficult to hear lyrics and other words correctly, and even the rare omission of sounds such as the background vocals in one of Trinity Seven's openings.

Switch to XAudio backend for stereo.

**Comment by logarrhythmic** [comment]
Oh! That's my biggest problem with Aegisub solved, then. Thanks!
