### ISSUE TITLE
libass does not render font manager loaded fonts

### ISSUE THREAD

**Issue by Ristellise** [Ristellise/AegisubDC#2]
Aegisub detects it, but for some reason, libass fail to recognize the font and defaults to arial.  
Unable to reproduce locally, but petzku have this issue.

**Comment by petzku** [comment]
Reproduced on Windows 10 Pro N insider preview using Fontbase.

Edition: Windows 10 Pro N Insider Preview
Version: 2004
OS build: 20221.1000

Fontbase version 2.13.2.

libass has the issue:
![image](https://user-images.githubusercontent.com/5639335/95037735-a706b480-06d4-11eb-86ee-d6d61d671d8a.png)

However, vsfilter does not (image uses vsfiltermod, but this did not affect the result):
![image](https://user-images.githubusercontent.com/5639335/95037737-aa9a3b80-06d4-11eb-9528-235d58432e7c.png)

The font picker also works as expected (I would expect it does not use the selected renderer at all):
![image](https://user-images.githubusercontent.com/5639335/95037826-fea52000-06d4-11eb-9c32-9f169526cfb5.png)

But the issue also happens in the style editor: 
![image](https://user-images.githubusercontent.com/5639335/95037846-1381b380-06d5-11eb-89e1-5e06972cda24.png)

At least AegisubDC versions r9205 and r9206 have this issue on my machine.

**Comment by begna112** [comment]
I have the same issue with Extensis Suitcase Fusion. 

I found that switching between subtitle renderers (libass/vsfliter), you're able to "refresh" the fonts so they display. 

Is this some kind of caching mechanism? If so, could a button be added to force a refresh of the renderer?

**Comment by begna112** [comment]
further testing shows that Fontbase is even more impaired than extensis. Cycling the subtitle renderer does not resolve for Fontbase activated fonts. Possibly because of the method it registers the fonts in the registry.

Extensis
https://i.ddy.moe/2020/12/RegCool_201212-111247.png

FontBase
https://i.ddy.moe/2020/12/RegCool_201212-111423.png

**Comment by begna112** [comment]
Additionally, it's worth noting that Ryan's latest build of Aegisub from [here](https://github.com/TypesettingTools/Aegisub) ([binary](https://sharex.thevacuumof.space/2019/09/aegisub64.exe)), has an even better handling of the issue where the subtitle renderer doesn't even need to be cycled. 

DC build behavior:
[https://i.ddy.moe/2020/12/gkkVQwqLYY.mp4](https://i.ddy.moe/2020/12/gkkVQwqLYY.mp4)

Ryan's build behavior:
[https://i.ddy.moe/2020/12/fYU24tAlgT.mp4](https://i.ddy.moe/2020/12/fYU24tAlgT.mp4)

**Comment by Ristellise** [comment]
9211 should hopefully fix more font issues. closing for now since original issue has been fixed. @begna112, reopen a issue for the additional issue. Thanks
