### ISSUE TITLE
VSFilterMod appears to randomly crash on subtitles files.

### ISSUE THREAD

**Issue by Ristellise** [Ristellise/AegisubDC#22]
This seems to happen also on `9210` before the update to the newest VSFiltermod, maybe consider removing vsfiltermod from main distribution?

**Comment by Masaiki** [comment]
This may help
https://github.com/Masaiki/VSFilterMod/releases/tag/r5.2.4

**Comment by Ristellise** [comment]
Sorry for the wait, updated it on my end.

**Comment by Ristellise** [comment]
Fixed with Release 9213, now it also defaults to libass properly.
