### ISSUE TITLE
Implement RTL Support from wangqr's build

### ISSUE THREAD

**Issue by Samo99** [Ristellise/AegisubDC#24]
Hey man

Can you please implement this Fix in your build

https://github.com/wangqr/Aegisub/issues/81#issuecomment-813001228

**Comment by Ristellise** [comment]
Eventually.Currebtly swamped with other stuff.

**Comment by Samo99** [comment]
> Eventually. Currently swamped with other stuff.

Thank you so much.
That fix is so important for hundreds of  thousands of fansubbers that uses RTL laguneges.

**Comment by Ristellise** [comment]
> > Eventually. Currently swamped with other stuff.
> 
> Thank you so much.
> That fix is so important for hundreds of thousands of fansubbers that uses RTL laguneges.

Sorry to ask, but how many people really need this feature? I'd like to know some numbers. Because there aren't that many fansubbers in the english community either.

**Comment by Samo99** [comment]
In the Arabic community there are more than 14 fansub team and envry team have from 6 to 10 members.
 
And don't forget the Hebrew, Persians and urdo that are LTR languages also.

But i' still waiting for wangqr answer in https://github.com/wangqr/Aegisub/issues/101#issue-854710265
because of the punctuation issue if there is a fix for it.

**Comment by Ristellise** [comment]
> every team have from 6 to 10 members.
Its possible for teams to have the same members as it is very common in the english fansubbing community.  
So I found your statement "hundreds and thousands of fansubbers" to be rather untrue.

**Comment by Samo99** [comment]
> IRL

Will when i said hundreds of hothouses of fansubbers i meant not just the teams but also the ones that uses the app for fixing the sub the already there for themselves and in a population more than half a billion is rather a small number.

But Thanks and no one is rushing you for anything.

**Comment by Ristellise** [comment]
Implemented with Release 9213
