### ISSUE TITLE
Automation scripts that have decimal values boxes to type are displaying incorrectly.

### ISSUE THREAD

**Issue by Arex-M** [Ristellise/AegisubDC#25]
![image](https://user-images.githubusercontent.com/81535518/114285390-bddfe800-9a24-11eb-8880-a2af383e6c13.png)
For some reason, the box next to the checkbox Blur is displaying 1.00 instead of 0.01. Other automations scripts also have this the same issue.

**Comment by Ristellise** [comment]
> ![image](https://user-images.githubusercontent.com/81535518/114285390-bddfe800-9a24-11eb-8880-a2af383e6c13.png)
> For some reason, the box next to the checkbox Blur is displaying 1.00 instead of 0.01. Other automations scripts also have this the same issue.

inside Aegisub Motion:
`step: 0.01,             value: 1,`
The Step is 0.01 which is correct, same for the values as well.
