### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by PhyX-Meow** [Ristellise/AegisubDC#26]
Will this project support languages other than English, for example, Chinese?
Many language including Chinese is available in original Aegisub, so it seems easy to copy them here.
And if there is a plan to add other languages, how can I contribute to the translation?
Cheers.

**Comment by Ristellise** [comment]
> Will this project support languages other than English, for example, Chinese?
> Many language including Chinese is available in original Aegisub, so it seems easy to copy them here.
> And if there is a plan to add other languages, how can I contribute to the translation?
> Cheers.

In the `9212` release, there is a `locale.zip` unzip the zip directly into your aegisub installation folder, it should create a `locale` folder when unzipped. From then, you may select your preferred language.
