### ISSUE TITLE
Selecting either clip tool causes Aegisub 9213 to hang

### ISSUE THREAD

**Issue by sekukun** [Ristellise/AegisubDC#32]
Aegisub 9213 hangs whenever I select the rectangular or vector clip functions. This seems to happen for any videos I test including dummy video, and for any scripts loaded including blank ones.

This issue does not occur for me in 9210 or 9212. The file attached is an example of one generated in AppData/Roaming/Aegisub/log when I trigger the issue and force the program to close. Let me know if any other information would be helpful.

EDIT: Just for clarity, let me also confirm that all Aegisub versions tested are portable and use the same files in AppData for history, addons, etc.

[2021-08-03-14-03-17-a270.txt](https://github.com/Ristellise/AegisubDC/files/6926289/2021-08-03-14-03-17-a270.txt)

**Comment by Samo99** [comment]
Well that's weird, i use the clip function in a daily bases and i never experienced what happened to you.

**Comment by Ristellise** [comment]
Update 9213. Patch has been released to fix clip issues.

**Comment by Ristellise** [comment]
Closing due to lack of response
