### ISSUE TITLE
Number of Characters in the Longest Line of this Subtitle Counter not Working

### ISSUE THREAD

**Issue by MadokaAyukawa** [Ristellise/AegisubDC#33]
This counter does not seem to update automatically in 9213. In the SS below it's at zero, and it stay at zero when you click on other lines as well.

![image](https://user-images.githubusercontent.com/44476321/129990250-e535787d-021f-452b-9a0b-27b9ff93cf55.png)

**Comment by Ristellise** [comment]
Fixed in 9213E, grab the F release.
