### ISSUE TITLE
Updating old Indonesian UI 

### ISSUE THREAD

**Issue by doplank** [Ristellise/AegisubDC#38]
Hi there, AegisubDC dev, I'm Rahmat Bambang, the original Indonesian translator for Aegisub 3.2.2, a decade ago I started translating Aegisub UI into Indonesian language, but I found out that the original development has been in stopped for years and I cannot update the new string or improve my translation since then. And I found your Aegisub by a chance and still active in development. So, is there any way to update the .po and .mo files to your current project? If you have an email, I'll send it to you. Thank you.

**Comment by doplank** [comment]
Hello, thanks for the respond. Here's the updated Indonesian UI for AegisubDC

[https://files.catbox.moe/o80w1m.zip](url)

Thank you.

**Comment by Ristellise** [comment]
Hi,

Thanks for the update. I'll get to it when I have the time (probably next week).

**Comment by Ristellise** [comment]
new localization now uploaded.
