### ISSUE TITLE
Positioning error in some situations

### ISSUE THREAD

**Issue by SSgumS** [Ristellise/AegisubDC#40]
Hello

There is some positioning error in the latest release (I don't know it was present in the last releases or not).
As we can see in the pictures, positioning is correct in mpv and Aegisub r8903+1. But it's not at the right position in AegisubDC.
The used font is attached to the subtitle file. Subtitle renderer has been set to libass in both Aegisubs.

Sample subtitle:
[sub-01.zip](https://github.com/Ristellise/AegisubDC/files/7642604/sub-01.zip)

Pictures:
![sub-mpv](https://user-images.githubusercontent.com/25867589/144439645-0ff78b60-ae73-4f60-aec3-dfee508a873d.PNG)
![sub-r8903](https://user-images.githubusercontent.com/25867589/144439297-33e0bcda-54a9-4b19-8e95-af71c89621d3.PNG)
![sub-aegisubdc](https://user-images.githubusercontent.com/25867589/144438849-95caee6b-8792-4dd9-b335-46f5cb3efdad.PNG)

**Comment by Ristellise** [comment]
Hi! Can you try wangqr builds and see which version it has changes in? Thanks. Since this bug existed even before 9201.

**Comment by astiob** [comment]
Do you have other fonts named `IRANSansWeb` (besides the one embedded in the subtitle file) installed on the same computer?

**Comment by SSgumS** [comment]
> Do you have other fonts named `IRANSansWeb` (besides the one embedded in the subtitle file) installed on the same computer?

No, I don't have any different font with the same name. The installed one and the font attached are identical to each other.
However, based on the discussion in [libass/libass#576](https://github.com/libass/libass/issues/576) it seems that the problem was because of the older version of libass that has been used in AegisubDC.
Thanks, everyone.

**Comment by SSgumS** [comment]
fixed on 9215 because of the updated libass binary.
