### ISSUE TITLE
Enhancement for Font Collector 

### ISSUE THREAD

**Issue by Samo99** [Ristellise/AegisubDC#42]
Is there any way to make the font collector recognize the fonts that are located in special nexusfont folder and not only the installed ones?

**Comment by Ristellise** [comment]
Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative

**Comment by Samo99** [comment]
> Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative

Maybe you misunderstood me, what i meant was to make the font collector grab the fonts from nexusfont folder or FontBase folder and not only the fonts that are installed in the system,

**Comment by Ristellise** [comment]
> > Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative
> 
> Maybe you misunderstood me, what i meant was to make the font collector grab the fonts from nexusfont folder or FontBase folder and not only the fonts that are installed in the system,

My point still stands, font collector also loads from fontbase if it finds it, unless it doesn't which I'll be bit confused.

**Comment by Samo99** [comment]
> > > Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative
> > 
> > 
> > Maybe you misunderstood me, what i meant was to make the font collector grab the fonts from nexusfont folder or FontBase folder and not only the fonts that are installed in the system,
> 
> My point still stands, font collector also loads from fontbase if it finds it, unless it doesn't which I'll be bit confused.

Yeah that's what i'm saying, you can load the fonts in style editor and when you play the video inside aegisub but when it comes to font collector it can't grap the fonts unless they are installed in system.

![التق اط](https://user-images.githubusercontent.com/12115578/149012267-7c9d03f4-ba80-4f65-85e9-47151d4af306.PNG)

![التقاط](https://user-images.githubusercontent.com/12115578/149012301-58387590-f7d6-46e0-8f0b-b63f54c38dfa.PNG)

**Comment by Ristellise** [comment]
> > > > Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative
> > > 
> > > 
> > > Maybe you misunderstood me, what i meant was to make the font collector grab the fonts from nexusfont folder or FontBase folder and not only the fonts that are installed in the system,
> > 
> > 
> > My point still stands, font collector also loads from fontbase if it finds it, unless it doesn't which I'll be bit confused.
> 
> Yeah that's what i'm saying, you can load the fonts in style editor and when you play the video inside aegisub but when it comes to font collector it can't grap the fonts unless they are installed in system.
> 
> ![التق اط](https://user-images.githubusercontent.com/12115578/149012267-7c9d03f4-ba80-4f65-85e9-47151d4af306.PNG)
> 
> ![التقاط](https://user-images.githubusercontent.com/12115578/149012301-58387590-f7d6-46e0-8f0b-b63f54c38dfa.PNG)

Unless im going crazy, but it this isn't true. it works fine on my end with FontBase. I just tested it.

**Comment by Samo99** [comment]
> > > > > Not really a task for the font collector but more on the user side. Install a [font manager](https://fontba.se/) as an alternative
> > > > 
> > > > 
> > > > Maybe you misunderstood me, what i meant was to make the font collector grab the fonts from nexusfont folder or FontBase folder and not only the fonts that are installed in the system,
> > > 
> > > 
> > > My point still stands, font collector also loads from fontbase if it finds it, unless it doesn't which I'll be bit confused.
> > 
> > 
> > Yeah that's what i'm saying, you can load the fonts in style editor and when you play the video inside aegisub but when it comes to font collector it can't grap the fonts unless they are installed in system.
> > ![التق اط](https://user-images.githubusercontent.com/12115578/149012267-7c9d03f4-ba80-4f65-85e9-47151d4af306.PNG)
> > ![التقاط](https://user-images.githubusercontent.com/12115578/149012301-58387590-f7d6-46e0-8f0b-b63f54c38dfa.PNG)
> 
> Unless im going crazy, but it this isn't true. it works fine on my end with FontBase. I just tested it.

I tested it again but now i enabled the folder in FontBase to activate it and it worked perfectly.
Thanks man :)
