### ISSUE TITLE
Portable builds?

### ISSUE THREAD

**Issue by nlboom** [Ristellise/AegisubDC#46]
Official builds of Aegisub had a portable versions. Is it possible to do the same in this fork too?

**Comment by Ristellise** [comment]
Entire zip file is portable, but configs are stored locally.

**Comment by nlboom** [comment]
I would like the program files and configs to be stored in one single folder.

**Comment by nlboom** [comment]
> 

I would like the program files and configs to be stored in one single folder.

**Comment by Ristellise** [comment]
> > 
> 
> I would like the program files and configs to be stored in one single folder.

Should be possible to make the entire install portable by copying `config.json` to the same folder as `Aegisub.exe`
