### ISSUE TITLE
Question about libass renderer or patches

### ISSUE THREAD

**Issue by TheOneric** [Ristellise/AegisubDC#54]
I noticed something odd about your builds and was wondering whether you happen to have an idea of what’s going on. If not it’s ~~hopefully~~ probably harmless and fine to leave as is.

I was looking at backporting https://github.com/wangqr/Aegisub/pull/134 to fix the libass backend to AegisubDC, but surprisingly the r9215B binary *somehow* already renders the sample *(see linked PR)* correctly — eventhough the [current sourcecode](https://github.com/Ristellise/AegisubDC/commit/35db2ad6c0b64599249175ed6904010f200e0be2) here on GitHub does never call `ass_set_storage_size`. The r9214 binaries still render it as expected (i.e. wrong).

I looked a bit through the code but didn't find anything explaining why the rendering appears correct with r9215. Did you apply some other patch to the vendored libass which might cause this? Potentially such a patch could have detrimental effects on other samples even if it works out well here. Or maybe you did apply the same patch as in the linked PR for the binary build and just forgot to push it to GitHub?

To visualise, here’s how it looks in r9214 and how I'd exepect r9215B to look based on the source:
![aegisubdc_9214](https://user-images.githubusercontent.com/1668471/168157714-0a74058e-dc05-41ea-ab9c-0adfc2516008.png)

But here's what r9215B actually looks like and how I'd expect the current source to look **after** the patch has been applied:
![aegisubdc_9215](https://user-images.githubusercontent.com/1668471/168157855-89bd45ea-f0a0-4631-87fb-9a4b8dc2f7b9.png)

*Note: the sample is intended for use with [DejaVu fonts](https://dejavu-fonts.github.io/) in case you want to exactly reproduce it*

**Comment by astiob** [comment]
Sorry to be a bother, but am I guessing correctly that the patch is in the last binary but still not in the GitHub source repo? Could you perhaps push it? Just so, you know, the public sources match the binaries.

**Comment by Ristellise** [comment]
> Sorry to be a bother, but am I guessing correctly that the patch is in the last binary but still not in the GitHub source repo? Could you perhaps push it? Just so, you know, the public sources match the binaries.

Will do as soon as I get around it. My focus for sub editors is starting to drift towards Ameko, so yeah.
